
vich_uploader:
    db_driver: orm
    mappings:
        publications:
            uri_prefix: /images/publications
            upload_destination: '%kernel.project_dir%/public/images/publications'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true

