app_publication_showback:
    path: '/publication/{id}'
    controller: 'App\Controller\PublicationController::show'
    methods: ['GET']

app_publication_showfront:
    path: '/front/publication/{id}'
    controller: 'App\Controller\PublicationController::showFront'
    methods: ['GET']

app_like_publication:
    path: '/publication/{id}/like'
    controller: 'App\Controller\PublicationController::likePublication'
    methods: ['POST']