#index:
#    path: /
#    controller: App\Controller\DefaultController::index


country_info:
  path: '/country/{countryCode}'
  controller: 'App\Controller\CountryController::index'
  requirements:
    countryCode: '[A-Za-z]+'
