index:
    path: /
    controller: App\Controller\DefaultController::index

app_publication_show_comments:
    path: '/publication/{id}/show_comments'
    controller: 'App\Controller\PublicationController::show_comments'
    methods: ['GET']

app_publication_search_ajax:
    path: '/publication/search-ajax'
    controller: 'App\Controller\YourController::searchAjax'
    methods: ['GET']


chatbot:
    path: '/chatbot'
    controller: 'App\Controller\ChatbotController::handleChatbotRequest'
    methods: ['POST']