# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    twilio_account_sid: 'ACe6b91492b768c01136f3df2ee76d14d9'
    twilio_auth_token: 'b747491e81b2ea8ba7a2ff9dde989818'
    twilio_phone_number: '+14013714143'
    image_file_directory: '%kernel.project_dir%/public/uploads/images'
    image_directory: '%kernel.project_dir%/public/uploads/images'

services:
    App\Service\CountryInfoService: ~
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\Service\BadWordsChecker: ~
    App\Controller\APIOfferReviewController:
        autowire: true
        autoconfigure: true
        public: true
    App\Service\CloudinaryFactory:
        class: App\Service\CloudinaryFactory
        arguments:
            $container: '@service_container'

    Cloudinary\Cloudinary:
        factory: ['@App\Service\CloudinaryFactory', 'create']
    
   
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # config/services.yaml


